let constituencies = ['Aberavon',
'Aberconwy',
'Aberdeen North',
'Aberdeen South',
'West Aberdeenshire and Kincardine',
'Airdrie and Shotts',
'Aldershot',
'Aldridge-Brownhills',
'Altrincham and Sale West',
'Alyn and Deeside',
'Amber Valley',
'Angus',
'East Antrim',
'North Antrim',
'South Antrim',
'Arfon',
'Argyll and Bute',
'Arundel and South Downs',
'Ashfield',
'Ashford',
'Ashton-under-Lyne',
'Aylesbury',
'Ayr, Carrick and Cumnock',
'Central Ayrshire',
'North Ayrshire and Arran',
'Banbury',
'Banff and Buchan',
'Barking',
'Barnsley Central',
'Barnsley East',
'Barrow and Furness',
'Basildon and Billericay',
'South Basildon and East Thurrock',
'Basingstoke',
'Bassetlaw',
'Bath',
'Batley and Spen',
'Battersea',
'Beaconsfield',
'Beckenham',
'Bedford',
'Mid Bedfordshire',
'North East Bedfordshire',
'South West Bedfordshire',
'Belfast East',
'Belfast North',
'Belfast South',
'Belfast West',
'Bermondsey and Old Southwark',
'Berwickshire, Roxburgh and Selkirk',
'Berwick-upon-Tweed',
'Bethnal Green and Bow',
'Beverley and Holderness',
'Bexhill and Battle',
'Bexleyheath and Crayford',
'Birkenhead',
'Birmingham, Edgbaston',
'Birmingham, Erdington',
'Birmingham, Hall Green',
'Birmingham, Hodge Hill',
'Birmingham, Ladywood',
'Birmingham, Northfield',
'Birmingham, Perry Barr',
'Birmingham, Selly Oak',
'Birmingham, Yardley',
'Bishop Auckland',
'Blackburn',
'Blackley and Broughton',
'Blackpool North and Cleveleys',
'Blackpool South',
'Blaenau Gwent',
'Blaydon',
'Blyth Valley',
'Bognor Regis and Littlehampton',
'Bolsover',
'Bolton North East',
'Bolton South East',
'Bolton West',
'Bootle',
'Boston and Skegness',
'Bosworth',
'Bournemouth East',
'Bournemouth West',
'Bracknell',
'Bradford East',
'Bradford South',
'Bradford West',
'Braintree',
'Brecon and Radnorshire',
'Brent Central',
'Brent North',
'Brentford and Isleworth',
'Brentwood and Ongar',
'Bridgend',
'Bridgwater and West Somerset',
'Brigg and Goole',
'Brighton, Kemptown',
'Brighton, Pavilion',
'Bristol East',
'Bristol North West',
'Bristol South',
'Bristol West',
'Broadland',
'Bromley and Chislehurst',
'Bromsgrove',
'Broxbourne',
'Broxtowe',
'Buckingham',
'Burnley',
'Burton',
'Bury North',
'Bury South',
'Bury St Edmunds',
'Caerphilly',
'Caithness, Sutherland and Easter Ross',
'Calder Valley',
'Camberwell and Peckham',
'Camborne and Redruth',
'Cambridge',
'North East Cambridgeshire',
'North West Cambridgeshire',
'South Cambridgeshire',
'South East Cambridgeshire',
'Cannock Chase',
'Canterbury',
'Cardiff Central',
'Cardiff North',
'Cardiff South and Penarth',
'Cardiff West',
'Carlisle',
'Carmarthen East and Dinefwr',
'Carmarthen West and South Pembrokeshire',
'Carshalton and Wallington',
'Castle Point',
'Ceredigion',
'Charnwood',
'Chatham and Aylesford',
'Cheadle',
'Chelmsford',
'Chelsea and Fulham',
'Cheltenham',
'Chesham and Amersham',
'City of Chester',
'Chesterfield',
'Chichester',
'Chingford and Woodford Green',
'Chippenham',
'Chipping Barnet',
'Chorley',
'Christchurch',
'Cities of London and Westminster',
'Clacton',
'Cleethorpes',
'Clwyd South',
'Clwyd West',
'Coatbridge, Chryston and Bellshill',
'Colchester',
'Colne Valley',
'Congleton',
'Copeland',
'Corby',
'North Cornwall',
'South East Cornwall',
'The Cotswolds',
'Coventry North East',
'Coventry North West',
'Coventry South',
'Crawley',
'Crewe and Nantwich',
'Croydon Central',
'Croydon North',
'Croydon South',
'Cumbernauld, Kilsyth and Kirkintilloch East',
'Cynon Valley',
'Dagenham and Rainham',
'Darlington',
'Dartford',
'Daventry',
'Delyn',
'Denton and Reddish',
'Derby North',
'Derby South',
'Derbyshire Dales',
'Mid Derbyshire',
'North East Derbyshire',
'South Derbyshire',
'Devizes',
'Central Devon',
'East Devon',
'North Devon',
'South West Devon',
'Torridge and West Devon',
'Dewsbury',
'Don Valley',
'Doncaster Central',
'Doncaster North',
'Mid Dorset and North Poole',
'North Dorset',
'South Dorset',
'West Dorset',
'Dover',
'Dudley North',
'Dudley South',
'Dulwich and West Norwood',
'Dumfries and Galloway',
'Dumfriesshire, Clydesdale and Tweeddale',
'East Dunbartonshire',
'West Dunbartonshire',
'Dundee East',
'Dundee West',
'Dunfermline and West Fife',
'North Durham',
'North West Durham',
'City of Durham',
'Dwyfor Meirionnydd',
'Ealing Central and Acton',
'Ealing North',
'Ealing, Southall',
'Easington',
'East Ham',
'East Kilbride, Strathaven and Lesmahagow',
'East Londonderry',
'East Lothian',
'Eastbourne',
'Eastleigh',
'Eddisbury',
'Edinburgh East',
'Edinburgh North and Leith',
'Edinburgh South',
'Edinburgh South West',
'Edinburgh West',
'Edmonton',
'Ellesmere Port and Neston',
'Elmet and Rothwell',
'Eltham',
'Enfield North',
'Enfield, Southgate',
'Epping Forest',
'Epsom and Ewell',
'Erewash',
'Erith and Thamesmead',
'Esher and Walton',
'Exeter',
'Falkirk',
'Fareham',
'Faversham and Mid Kent',
'Feltham and Heston',
'Fermanagh and South Tyrone',
'North East Fife',
'Filton and Bradley Stoke',
'Finchley and Golders Green',
'Folkestone and Hythe',
'Forest of Dean',
'Foyle',
'Fylde',
'Gainsborough',
'Garston and Halewood',
'Gateshead',
'Gedling',
'Gillingham and Rainham',
'Glasgow Central',
'Glasgow East',
'Glasgow North',
'Glasgow North East',
'Glasgow North West',
'Glasgow South',
'Glasgow South West',
'Glenrothes',
'Gloucester',
'Gordon',
'Gosport',
'Gower',
'Grantham and Stamford',
'Gravesham',
'Great Grimsby',
'Great Yarmouth',
'Greenwich and Woolwich',
'Guildford',
'Hackney North and Stoke Newington',
'Hackney South and Shoreditch',
'Halesowen and Rowley Regis',
'Halifax',
'Haltemprice and Howden',
'Halton',
'Hammersmith',
'East Hampshire',
'North East Hampshire',
'North West Hampshire',
'Hampstead and Kilburn',
'Harborough',
'Harlow',
'Harrogate and Knaresborough',
'Harrow East',
'Harrow West',
'Hartlepool',
'Harwich and North Essex',
'Hastings and Rye',
'Havant',
'Hayes and Harlington',
'Hazel Grove',
'Hemel Hempstead',
'Hemsworth',
'Hendon',
'Henley',
'Hereford and South Herefordshire',
'North Herefordshire',
'Hertford and Stortford',
'North East Hertfordshire',
'South West Hertfordshire',
'Hertsmere',
'Hexham',
'Heywood and Middleton',
'High Peak',
'Hitchin and Harpenden',
'Holborn and St Pancras',
'Hornchurch and Upminster',
'Hornsey and Wood Green',
'Horsham',
'Houghton and Sunderland South',
'Hove',
'Huddersfield',
'Kingston upon Hull East',
'Kingston upon Hull North',
'Kingston upon Hull West and Hessle',
'Huntingdon',
'Hyndburn',
'Ilford North',
'Ilford South',
'Inverclyde',
'Inverness, Nairn, Badenoch and Strathspey',
'Ipswich',
'Isle of Wight',
'Islington North',
'Islington South and Finsbury',
'Islwyn',
'Jarrow',
'Keighley',
'Kenilworth and Southam',
'Kensington',
'Kettering',
'Kilmarnock and Loudoun',
'Kingston and Surbiton',
'Kingswood',
'Kirkcaldy and Cowdenbeath',
'Knowsley',
'Lagan Valley',
'Lanark and Hamilton East',
'West Lancashire',
'Lancaster and Fleetwood',
'Leeds Central',
'Leeds East',
'Leeds North East',
'Leeds North West',
'Leeds West',
'Leicester East',
'Leicester South',
'Leicester West',
'North West Leicestershire',
'South Leicestershire',
'Leigh',
'Lewes',
'Lewisham East',
'Lewisham West and Penge',
'Lewisham, Deptford',
'Leyton and Wanstead',
'Lichfield',
'Lincoln',
'Linlithgow and East Falkirk',
'Liverpool, Riverside',
'Liverpool, Walton',
'Liverpool, Wavertree',
'Liverpool, West Derby',
'Livingston',
'Llanelli',
'Loughborough',
'Louth and Horncastle',
'Ludlow',
'Luton North',
'Luton South',
'Macclesfield',
'Maidenhead',
'Maidstone and The Weald',
'Makerfield',
'Maldon',
'Manchester Central',
'Manchester, Gorton',
'Manchester, Withington',
'Mansfield',
'Meon Valley',
'Meriden',
'Merthyr Tydfil and Rhymney',
'Mid Ulster',
'Middlesbrough',
'Middlesbrough South and East Cleveland',
'Midlothian',
'Milton Keynes North',
'Milton Keynes South',
'Mitcham and Morden',
'Mole Valley',
'Monmouth',
'Montgomeryshire',
'Moray',
'Morecambe and Lunesdale',
'Morley and Outwood',
'Motherwell and Wishaw',
'Na h-Eileanan an Iar',
'Neath',
'New Forest East',
'New Forest West',
'Newark',
'Newbury',
'Newcastle upon Tyne Central',
'Newcastle upon Tyne East',
'Newcastle upon Tyne North',
'Newcastle-under-Lyme',
'Newport East',
'Newport West',
'Newry and Armagh',
'Newton Abbot',
'Mid Norfolk',
'North Norfolk',
'North West Norfolk',
'South Norfolk',
'South West Norfolk',
'Normanton, Pontefract and Castleford',
'North Down',
'Northampton North',
'Northampton South',
'South Northamptonshire',
'Norwich North',
'Norwich South',
'Nottingham East',
'Nottingham North',
'Nottingham South',
'Nuneaton',
'Ochil and South Perthshire',
'Ogmore',
'Old Bexley and Sidcup',
'Oldham East and Saddleworth',
'Oldham West and Royton',
'Orkney and Shetland',
'Orpington',
'Oxford East',
'Oxford West and Abingdon',
'Paisley and Renfrewshire North',
'Paisley and Renfrewshire South',
'Pendle',
'Penistone and Stocksbridge',
'Penrith and The Border',
'Perth and North Perthshire',
'Peterborough',
'Plymouth, Moor View',
'Plymouth, Sutton and Devonport',
'Pontypridd',
'Poole',
'Poplar and Limehouse',
'Portsmouth North',
'Portsmouth South',
'Preseli Pembrokeshire',
'Preston',
'Pudsey',
'Putney',
'Rayleigh and Wickford',
'Reading East',
'Reading West',
'Redcar',
'Redditch',
'Reigate',
'East Renfrewshire',
'Rhondda',
'Ribble Valley',
'Richmond (Yorks)',
'Richmond Park',
'Rochdale',
'Rochester and Strood',
'Rochford and Southend East',
'Romford',
'Romsey and Southampton North',
'Ross, Skye and Lochaber',
'Rossendale and Darwen',
'Rother Valley',
'Rotherham',
'Rugby',
'Ruislip, Northwood and Pinner',
'Runnymede and Weybridge',
'Rushcliffe',
'Rutherglen and Hamilton West',
'Rutland and Melton',
'Saffron Walden',
'Salford and Eccles',
'Salisbury',
'Scarborough and Whitby',
'Scunthorpe',
'Sedgefield',
'Sefton Central',
'Selby and Ainsty',
'Sevenoaks',
'Sheffield Central',
'Sheffield South East',
'Sheffield, Brightside and Hillsborough',
'Sheffield, Hallam',
'Sheffield, Heeley',
'Sherwood',
'Shipley',
'Shrewsbury and Atcham',
'North Shropshire',
'Sittingbourne and Sheppey',
'Skipton and Ripon',
'Sleaford and North Hykeham',
'Slough',
'Solihull',
'North Somerset',
'North East Somerset',
'Somerton and Frome',
'South Down',
'South Holland and The Deepings',
'South Ribble',
'South Shields',
'Southampton, Itchen',
'Southampton, Test',
'Southend West',
'Southport',
'Spelthorne',
'St Albans',
'St Austell and Newquay',
'St Helens North',
'St Helens South and Whiston',
'St Ives',
'Stafford',
'Staffordshire Moorlands',
'South Staffordshire',
'Stalybridge and Hyde',
'Stevenage',
'Stirling',
'Stockport',
'Stockton North',
'Stockton South',
'Stoke-on-Trent Central',
'Stoke-on-Trent North',
'Stoke-on-Trent South',
'Stone',
'Stourbridge',
'Strangford',
'Stratford-on-Avon',
'Streatham',
'Stretford and Urmston',
'Stroud',
'Central Suffolk and North Ipswich',
'Suffolk Coastal',
'South Suffolk',
'West Suffolk',
'Sunderland Central',
'East Surrey',
'Surrey Heath',
'South West Surrey',
'Mid Sussex',
'Sutton and Cheam',
'Sutton Coldfield',
'Swansea East',
'Swansea West',
'North Swindon',
'South Swindon',
'Tamworth',
'Tatton',
'Taunton Deane',
'Telford',
'Tewkesbury',
'North Thanet',
'South Thanet',
'Thirsk and Malton',
'Thornbury and Yate',
'Thurrock',
'Tiverton and Honiton',
'Tonbridge and Malling',
'Tooting',
'Torbay',
'Torfaen',
'Totnes',
'Tottenham',
'Truro and Falmouth',
'Tunbridge Wells',
'Twickenham',
'Tynemouth',
'North Tyneside',
'Upper Bann',
'Uxbridge and South Ruislip',
'Vale of Clwyd',
'Vale of Glamorgan',
'Vauxhall',
'Wakefield',
'Wallasey',
'Walsall North',
'Walsall South',
'Walthamstow',
'Wansbeck',
'Wantage',
'Warley',
'Warrington North',
'Warrington South',
'Warwick and Leamington',
'North Warwickshire',
'Washington and Sunderland West',
'Watford',
'Waveney',
'Wealden',
'Weaver Vale',
'Wellingborough',
'Wells',
'Welwyn Hatfield',
'Wentworth and Dearne',
'West Bromwich East',
'West Bromwich West',
'West Ham',
'West Tyrone',
'Westminster North',
'Westmorland and Lonsdale',
'Weston-super-Mare',
'Wigan',
'North Wiltshire',
'South West Wiltshire',
'Wimbledon',
'Winchester',
'Windsor',
'Wirral South',
'Wirral West',
'Witham',
'Witney',
'Woking',
'Wokingham',
'Wolverhampton North East',
'Wolverhampton South East',
'Wolverhampton South West',
'Worcester',
'Mid Worcestershire',
'West Worcestershire',
'Workington',
'Worsley and Eccles South',
'East Worthing and Shoreham',
'Worthing West',
'The Wrekin',
'Wrexham',
'Wycombe',
'Wyre and Preston North',
'Wyre Forest',
'Wythenshawe and Sale East',
'Yeovil',
'Ynys Môn',
'York Central',
'York Outer',
'East Yorkshire'];

console.log('loaded');
